name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Client Install
        working-directory: pkg/client
        run: npm install -w pkg/client
      - name: Client Build
        working-directory: pkg/client
        run: npm run build -w pkg/client
      - name: Test
        working-directory: pkg/client
        run: npm run test -w pkg/client --coverage --watchAll=false
      - uses: codecov/codecov-action@v1
        with:
          flags: unitests
